# Generated by Django 2.2.3 on 2019-09-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wineuser',
            name='winery',
        ),
    ]
