# Generated by Django 2.2.3 on 2019-08-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wineuser',
            name='age',
        ),
        migrations.AddField(
            model_name='wineuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
