# Generated by Django 2.2.3 on 2019-10-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191014_1110'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wineuser',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wineuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wineuser',
            name='language',
            field=models.IntegerField(choices=[(1, 'Spanish'), (2, 'English'), (3, 'French')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wineuser',
            name='phone',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
