# Generated by Django 2.2.3 on 2019-10-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191014_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wineuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('TOURIST', 'TOURIST'), ('WINERY', 'WINERY'), ('ADMIN', 'ADMIN')], default='TOURIST', max_length=20),
        ),
    ]
