# Generated by Django 2.2.3 on 2019-10-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191020_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wineuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='wineuser',
            name='language',
            field=models.CharField(choices=[('Spanish', 'Spanish'), ('English', 'English'), ('French', 'French')], max_length=8),
        ),
    ]
