# Generated by Django 2.2.4 on 2019-11-19 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191028_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wineuser',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Gender'),
        ),
        migrations.AlterField(
            model_name='wineuser',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Language'),
        ),
    ]
