# Generated by Django 2.2.3 on 2019-09-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='wine_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='api.WineLine'),
        ),
        migrations.AlterField(
            model_name='wineline',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_lines', to='api.Winery'),
        ),
    ]
