# Generated by Django 2.2.3 on 2019-09-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190921_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='varietal',
            field=models.CharField(choices=[('1', 'Malbec'), ('2', 'Cabernet Sauvignon'), ('3', 'Chardonnay'), ('4', 'Merlot'), ('5', 'Other')], default='4', max_length=20),
        ),
    ]
