# Generated by Django 2.2.3 on 2019-09-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190921_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winery',
            name='website',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
