# Generated by Django 2.2.3 on 2019-09-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190903_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='canceled',
            new_name='cancelled',
        ),
    ]
