# Generated by Django 2.2.3 on 2019-09-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190924_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winery',
            name='website',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
