# Generated by Django 2.2.3 on 2019-09-23 01:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('event', 'user')},
        ),
    ]
