# Generated by Django 2.2.3 on 2019-09-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190903_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winery',
            options={'verbose_name': 'Winery', 'verbose_name_plural': 'Wineries'},
        ),
        migrations.CreateModel(
            name='WineLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Winery')),
            ],
            options={
                'verbose_name': 'Wine-line',
                'verbose_name_plural': 'Wine-lines',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('varietal', models.CharField(choices=[(1, 'Cavernet Sauvignon'), (2, 'Chardonnay'), (3, 'Merlot'), (4, 'Other')], default='Other', max_length=20)),
                ('wine_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WineLine')),
                ('winery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Winery')),
            ],
        ),
    ]
