# Generated by Django 2.2.3 on 2019-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imageswinery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
