# Generated by Django 2.2.3 on 2019-09-14 15:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190907_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='winery',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='varietal',
            field=models.CharField(choices=[('1', 'Cavernet Sauvignon'), ('2', 'Chardonnay'), ('3', 'Merlot'), ('4', 'Other')], default='4', max_length=20),
        ),
    ]
