# Generated by Django 2.2.3 on 2019-10-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagesevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_event', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='imageswinery',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_winery', to='api.Winery'),
        ),
    ]
