# Generated by Django 2.2.3 on 2019-10-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191003_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='imagesevent',
            name='filefield',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imageswinery',
            name='filefield',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imageswinery',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Winery'),
        ),
    ]
