# Generated by Django 2.2.3 on 2019-10-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191014_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='winery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.Winery'),
        ),
    ]
