# Generated by Django 2.2.3 on 2019-10-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191019_0241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'EventCategories'},
        ),
        migrations.CreateModel(
            name='ImagesWines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filefield', models.FileField(upload_to='')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Wine')),
            ],
        ),
    ]
