# Generated by Django 2.2.3 on 2019-11-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191028_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoccurrence',
            name='cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
