# Generated by Django 2.2.4 on 2019-11-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191119_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varietal',
            old_name='name',
            new_name='value',
        ),
    ]
