# Generated by Django 2.2.3 on 2019-09-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190916_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='ammount_payed',
            new_name='paid_ammount',
        ),
    ]
