# Generated by Django 2.2.3 on 2019-09-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190916_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='paid_ammount',
            new_name='paid_amount',
        ),
    ]
