WINERY = 'WINERY'
TOURIST = 'TOURIST'

LANGUAGE_SPANISH = 'Spanish'
LANGUAGE_ENGLISH = 'English'
LANGUAGE_FRENCH = 'French'

GENDER_MALE = 'M'
GENDER_FEMALE = 'F'
GENDER_OTHER = 'X'

LANGUAGES = [
    (LANGUAGE_SPANISH, 'Spanish'),
    (LANGUAGE_ENGLISH, 'English'),
    (LANGUAGE_FRENCH, 'French'),
]

GENDERS = [
    (GENDER_MALE, 'Male'),
    (GENDER_FEMALE, 'Female'),
    (GENDER_OTHER, 'Other')
]
