WINERY = 'WINERY'
TOURIST = 'TOURIST'
ADMIN = 'ADMIN'

LANGUAGE_SPANISH = 1
LANGUAGE_ENGLISH = 2
LANGUAGE_FRENCH = 3

GENDER_MALE = 1
GENDER_FEMALE = 2
GENDER_OTHER = 3

LANGUAGES = [
    (LANGUAGE_SPANISH, 'Spanish'),
    (LANGUAGE_ENGLISH, 'English'),
    (LANGUAGE_FRENCH, 'French'),
]

GENDERS = [
    (GENDER_MALE, 'Male'),
    (GENDER_FEMALE, 'Female'),
    (GENDER_OTHER, 'Other')
]
